import test from "node:test";
import assert from "node:assert/strict";

import { getNodeDefinition } from "../src/index.js";

const EXPECTED_NODE_SPEC = Object.freeze({
  pulse: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  out: {
    layout: "single-in",
    inputs: 1,
    outputs: 0,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
  },
  mux: {
    layout: "multi-out-6",
    inputs: 1,
    outputs: 6,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
  },
  demux: {
    layout: "multi-in-6-mirrored",
    inputs: 6,
    outputs: 1,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
  },
  add: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  sub: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  set: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  speed: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  pitch: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  decay: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  crush: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  hpf: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  lpf: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  switch: {
    layout: "multi-out-6-control",
    inputs: 1,
    outputs: 6,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  block: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: false,
    defaultParam: 1,
  },
  every: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  drop: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  random: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  counter: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 8,
  },
  gtp: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  ltp: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  gtep: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  ltep: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
  match: {
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
  },
});

test("built-in registry metadata stays aligned with the node behavior table", () => {
  for (const [type, expected] of Object.entries(EXPECTED_NODE_SPEC)) {
    const definition = getNodeDefinition(type);

    assert.ok(definition, `Missing registry definition for ${type}.`);
    assert.deepEqual(
      {
        layout: definition.layout,
        inputs: definition.inputs,
        outputs: definition.outputs,
        controlPorts: definition.controlPorts,
        hasParam: definition.hasParam,
        defaultParam: definition.defaultParam,
      },
      expected,
      type,
    );
  }
});
