import {
  addSignal,
  blockControl,
  blockSignal,
  counterControl,
  counterSignal,
  createBlockState,
  createComparisonSignal,
  createConstantSignal,
  createCounterState,
  createEffectSignal,
  createEveryState,
  demuxSignal,
  everySignal,
  groupSignal,
  muxSignal,
  pulseSignal,
  randomSignal,
  setParamFromControl,
  setSignal,
  sinkSignal,
  speedSignal,
  subSignal,
  switchSignal,
} from "./behaviors/index.js";
import { buildPalette as buildPaletteItems } from "./palette.js";
import {
  createRegistryValidationError,
  validateRegistry,
} from "./validate-registry.js";
import { ARCHETYPES, getLayout, getPortSideSlot } from "./archetypes.js";

const CATEGORY_COLORS = {
  Sources: "#2a9d8f",
  Sinks: "#e9c46a",
  Routing: "#577590",
  Math: "#4d908e",
  Constants: "#6d597a",
  Modifiers: "#f9844a",
  State: "#9c6644",
  Logic: "#277da1",
  Groups: "#6c757d",
};

const NODE_TYPE_ALIASES = Object.freeze({
  multiplexer: "mux",
  demultiplexer: "demux",
});

function defineNode(definition) {
  return Object.freeze(definition);
}

function defineConstantNode(value) {
  return defineNode({
    type: `const${value}`,
    label: `Const ${value}`,
    description: `Overwrite the incoming value with the constant ${value}.`,
    category: "Constants",
    icon: `const${value}`,
    color: CATEGORY_COLORS.Constants,
    layout: "single-io",
    inputs: 1,
    outputs: 1,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
    onSignal: createConstantSignal(value),
    paletteOrder: 100 + value,
  });
}

function defineFilterNode({
  type,
  label,
  description,
  compare,
  paletteOrder,
  icon = type,
}) {
  return defineNode({
    type,
    label,
    description,
    category: "Logic",
    icon,
    color: CATEGORY_COLORS.Logic,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: createComparisonSignal(compare),
    paletteOrder,
  });
}

export const NODE_REGISTRY = Object.freeze([
  defineNode({
    type: "pulse",
    label: "Pulse",
    description: "Emit a fixed pulse value of 1 on the master clock using the current rate parameter.",
    category: "Sources",
    icon: "pulse",
    color: CATEGORY_COLORS.Sources,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: pulseSignal,
    paletteOrder: 10,
  }),
  defineNode({
    type: "output",
    label: "Output",
    description: "Consume pulses and hand them to the audio integration layer.",
    category: "Sinks",
    icon: "output",
    color: CATEGORY_COLORS.Sinks,
    layout: "single-in",
    inputs: 1,
    outputs: 0,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
    onSignal: sinkSignal,
    paletteOrder: 20,
  }),
  defineNode({
    type: "mux",
    label: "Mux",
    description: "Duplicate an incoming pulse to all six output ports.",
    category: "Routing",
    icon: "mux",
    color: CATEGORY_COLORS.Routing,
    layout: "multi-out-6",
    inputs: 1,
    outputs: 6,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
    onSignal: muxSignal,
    paletteOrder: 30,
  }),
  defineNode({
    type: "demux",
    label: "Demux",
    description: "Forward any of six inputs to a single output port.",
    category: "Routing",
    icon: "demux",
    color: CATEGORY_COLORS.Routing,
    layout: "multi-in-6-mirrored",
    inputs: 6,
    outputs: 1,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
    onSignal: demuxSignal,
    paletteOrder: 40,
  }),
  defineNode({
    type: "switch",
    label: "Switch",
    description: "Route the pulse to one of six outputs using the current selection value.",
    category: "Routing",
    icon: "switch",
    color: CATEGORY_COLORS.Routing,
    layout: "multi-out-6-control",
    inputs: 1,
    outputs: 6,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: switchSignal,
    paletteOrder: 50,
  }),
  defineNode({
    type: "block",
    label: "Block",
    description: "Pass or block pulses based on the most recent control input parity.",
    category: "Routing",
    icon: "block",
    color: CATEGORY_COLORS.Routing,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: false,
    defaultParam: 1,
    initState: createBlockState,
    onControl: blockControl,
    onSignal: blockSignal,
    paletteOrder: 60,
  }),
  defineNode({
    type: "add",
    label: "Add",
    description: "Add the current parameter to the incoming pulse value.",
    category: "Math",
    icon: "add",
    color: CATEGORY_COLORS.Math,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: addSignal,
    paletteOrder: 70,
  }),
  defineNode({
    type: "sub",
    label: "Subtract",
    description: "Subtract the current parameter from the incoming pulse value.",
    category: "Math",
    icon: "sub",
    color: CATEGORY_COLORS.Math,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: subSignal,
    paletteOrder: 80,
  }),
  defineNode({
    type: "set",
    label: "Set",
    description: "Replace the incoming pulse value with the current parameter.",
    category: "Math",
    icon: "set",
    color: CATEGORY_COLORS.Math,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: setSignal,
    paletteOrder: 90,
  }),
  ...Array.from({ length: 8 }, (_, index) => defineConstantNode(index + 1)),
  defineNode({
    type: "speed",
    label: "Speed",
    description: "Overwrite the pulse speed with the current parameter.",
    category: "Modifiers",
    icon: "speed",
    color: CATEGORY_COLORS.Modifiers,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: speedSignal,
    paletteOrder: 200,
  }),
  defineNode({
    type: "pitch",
    label: "Pitch",
    description: "Write a playback-speed value onto the pulse params.",
    category: "Modifiers",
    icon: "pitch",
    color: CATEGORY_COLORS.Modifiers,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    paramMap: {
      param: {
        target: "speed",
        mapping: "pitchTable",
        unit: "ratio",
      },
    },
    onSignal: createEffectSignal("pitch"),
    paletteOrder: 205,
  }),
  defineNode({
    type: "decay",
    label: "Decay",
    description: "Write a decay playback effect value onto the pulse params.",
    category: "Modifiers",
    icon: "decay",
    color: CATEGORY_COLORS.Modifiers,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    paramMap: {
      param: {
        target: "end",
        mapping: "endTable",
        unit: "ratio",
      },
    },
    onSignal: createEffectSignal("decay"),
    paletteOrder: 210,
  }),
  defineNode({
    type: "crush",
    label: "Crush",
    description: "Write a bit-crush playback effect value onto the pulse params.",
    category: "Modifiers",
    icon: "crush",
    color: CATEGORY_COLORS.Modifiers,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    paramMap: {
      param: {
        target: "crush",
        mapping: "crushTable",
        unit: "bits",
      },
    },
    onSignal: createEffectSignal("crush"),
    paletteOrder: 220,
  }),
  defineNode({
    type: "hpf",
    label: "HPF",
    description: "Write a high-pass filter playback effect value onto the pulse params.",
    category: "Modifiers",
    icon: "hpf",
    color: CATEGORY_COLORS.Modifiers,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    paramMap: {
      param: {
        target: "hpf",
        mapping: "hpfTable",
        unit: "hz",
      },
    },
    onSignal: createEffectSignal("hpf"),
    paletteOrder: 230,
  }),
  defineNode({
    type: "lpf",
    label: "LPF",
    description: "Write a low-pass filter playback effect value onto the pulse params.",
    category: "Modifiers",
    icon: "lpf",
    color: CATEGORY_COLORS.Modifiers,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    paramMap: {
      param: {
        target: "lpf",
        mapping: "lpfTable",
        unit: "hz",
      },
    },
    onSignal: createEffectSignal("lpf"),
    paletteOrder: 240,
  }),
  defineNode({
    type: "every",
    label: "Every",
    description: "Pass every Nth pulse and drop the others.",
    category: "State",
    icon: "every",
    color: CATEGORY_COLORS.State,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    initState: createEveryState,
    onSignal: everySignal,
    paletteOrder: 300,
  }),
  defineNode({
    type: "random",
    label: "Random",
    description: "Replace the incoming pulse value with a random integer up to the parameter.",
    category: "State",
    icon: "random",
    color: CATEGORY_COLORS.State,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    onControl: setParamFromControl,
    onSignal: randomSignal,
    paletteOrder: 310,
  }),
  defineNode({
    type: "counter",
    label: "Counter",
    description: "Count incoming pulses, resetting to the parameter when control fires.",
    category: "State",
    icon: "counter",
    color: CATEGORY_COLORS.State,
    layout: "single-io-control",
    inputs: 1,
    outputs: 1,
    controlPorts: 1,
    hasParam: true,
    defaultParam: 1,
    initState: createCounterState,
    onControl: counterControl,
    onSignal: counterSignal,
    paletteOrder: 320,
  }),
  defineFilterNode({
    type: "gtp",
    label: "Greater Than",
    description: "Pass the pulse when its value is greater than the parameter.",
    compare: (value, param) => value > param,
    paletteOrder: 400,
  }),
  defineFilterNode({
    type: "ltp",
    label: "Less Than",
    description: "Pass the pulse when its value is less than the parameter.",
    compare: (value, param) => value < param,
    paletteOrder: 410,
  }),
  defineFilterNode({
    type: "gtep",
    label: "Greater or Equal",
    description: "Pass the pulse when its value is greater than or equal to the parameter.",
    compare: (value, param) => value >= param,
    paletteOrder: 420,
  }),
  defineFilterNode({
    type: "ltep",
    label: "Less or Equal",
    description: "Pass the pulse when its value is less than or equal to the parameter.",
    compare: (value, param) => value <= param,
    paletteOrder: 430,
  }),
  defineFilterNode({
    type: "match",
    label: "Match",
    description: "Pass the pulse when its value exactly matches the parameter.",
    compare: (value, param) => value === param,
    paletteOrder: 440,
  }),
  defineNode({
    type: "group",
    label: "Group",
    description: "A project-defined grouped node placeholder with a custom derived layout.",
    category: "Groups",
    icon: "group",
    color: CATEGORY_COLORS.Groups,
    layout: "custom",
    inputs: 0,
    outputs: 0,
    controlPorts: 0,
    hasParam: false,
    defaultParam: 1,
    onSignal: groupSignal,
    hidden: true,
    paletteOrder: 900,
  }),
]);

export function buildRegistryIndex(registry = NODE_REGISTRY) {
  const validationResult = validateRegistry(registry);

  if (!validationResult.ok) {
    throw createRegistryValidationError(validationResult);
  }

  return new Map(registry.map((definition) => [definition.type, definition]));
}

export function buildPalette(registry = NODE_REGISTRY) {
  return buildPaletteItems(registry);
}

export function resolveCanonicalNodeType(type) {
  return NODE_TYPE_ALIASES[type] ?? type;
}

export function getNodeDefinition(type, index = buildRegistryIndex()) {
  return index.get(resolveCanonicalNodeType(type));
}

export { ARCHETYPES, getLayout, getPortSideSlot, validateRegistry };

if (process?.env?.NODE_ENV !== "production") {
  buildRegistryIndex(NODE_REGISTRY);
}
